data:
    data_dir: ../Datasets/CelebA/

model:
    MODEL_PATH: ./models/CBM/celebA_CBM_poly_3_10_0.500_2.pth
    MODEL_TYPE: CBM
    ENCODER: resnet18
    LAST_STAGE: poly
    POLY_POW: 3

results:
    VALS_PATH: ./results/TCAV_CBM/celebA_CBM_poly_3_10_0_500_2/
